# Generated by Django 5.1.7 on 2025-03-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
