# Generated by Django 5.1.7 on 2025-03-18 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothing_manufacturer'),
        ('producer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='clothing',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to='producer.producer'),
        ),
    ]
